FROM ubuntu:24.04

ARG TZ=Asia/Tokyo
ARG TEST_DIR=/app/test

# パッケージのインストール
RUN apt-get update && \
    apt-get install -y \
    tzdata iproute2 iputils-ping \
    gcc make vim && \
    rm -rf /var/lib/apt/lists/*

# タイムゾーンの設定
RUN ln -sf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone

# テストプログラムのソースコードをコンテナ内にコピー
COPY ./test $TEST_DIR

# テストプログラムのコンパイル
WORKDIR $TEST_DIR
RUN make

CMD ["/bin/bash"]