FROM ubuntu:24.04

ARG TEST_DIR=/app/test

# パッケージのインストール
RUN apt-get update && \
    apt-get install -y \
    iproute2 iputils-ping gcc make && \
    rm -rf /var/lib/apt/lists/*

# テストプログラムのソースコードをコンテナ内にコピー
COPY ./test $TEST_DIR

# テストプログラムのコンパイル
WORKDIR $TEST_DIR
RUN make

CMD ["/bin/bash"]